characters:
  Lindamayer:
    attack-cooldown-ticks: 60
    cd: 1800
    glowing-duration: 100
  Baphomet:
    attack-cooldown-ticks: 50
  Hein:
    attack-cooldown-ticks: 50
    wither-duration: 60
  Miranda:
    attack-cooldown-ticks: 110
    pearl-cooldown: 600
  RedHat:
    duration: 100
    regeneration-amplifier: 0
    resistance-amplifier: 0
  Victoria:
    cd: 1
    radius: 5
  Dodo:
    speed-duration: 60
  CheshireCat:
    speed-duration: 60
    speed-amplifier: 0
  Eunice:
    cd: 2000
    duration: 200
    speed-amplifier: 1
    regeneration-amplifier: 1
  FakeTurtle:
    resistance-amplifier: 1
    slowness-amplifier: 1
    jump-amplifier: 1
    soup-cooldown: 1800
    invisibility-duration: 100
  Leaf:
    item-obtain-cooldown: 600
  Bill:
    cd: 2400
    serpent-god-blood-obtain-cooldown: 3600
  Mabel:
    cd: 1500
    duration: 100